// LUMI VIỆT NAM - Mock Data
// Tác giả: Trần Minh Thương - Bộ phận T&S Miền Nam

const mockProducts = [
  {
    id: 1,
    dateReceived: "2024-01-15",
    dateSent: "2024-01-20",
    productCode: "LUMI-001",
    deviceName: "Lumi Smart Sensor Pro",
    distributor: "Nhà phân phối Miền Bắc",
    distributorPhone: "0901234567",
    distributorEmail: "mien-bac@lumi.vn",
    errorDescription:
      "Không kết nối được WiFi, đèn LED báo lỗi liên tục. Thiết bị không phản hồi khi kết nối qua ứng dụng mobile.",
    repairStatus: "completed",
    shippingStatus: "shipped",
    viettelTrackingCode: "115276011121",
    estimatedCompletion: "2024-01-20",
    actualCompletion: "2024-01-19",
    repairNotes: "Đã thay thế module WiFi và cập nhật firmware lên phiên bản mới nhất. Kiểm tra kết nối ổn định.",
    repairCost: 150000,
    partsCost: 150000,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    dateReceived: "2024-01-16",
    productCode: "LUMI-002",
    deviceName: "Lumi Gateway Controller",
    distributor: "Nhà phân phối Miền Nam",
    distributorPhone: "0902345678",
    distributorEmail: "mien-nam@lumi.vn",
    errorDescription:
      "LED báo lỗi liên tục, không nhận tín hiệu từ sensor. Gateway không thể điều khiển các thiết bị con.",
    repairStatus: "in-progress",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP240116002",
    estimatedCompletion: "2024-01-25",
    repairNotes: "Đang kiểm tra bo mạch chính và thay thế IC điều khiển",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2024-01-16T14:30:00Z",
  },
  {
    id: 3,
    dateReceived: "2024-01-17",
    productCode: "LUMI-003",
    deviceName: "Lumi Temperature Monitor",
    distributor: "Nhà phân phối Miền Trung",
    distributorPhone: "0903456789",
    distributorEmail: "mien-trung@lumi.vn",
    errorDescription: "Hiển thị sai nhiệt độ, chênh lệch 5-10 độ so với thực tế. Cảm biến nhiệt độ không chính xác.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP240117003",
    estimatedCompletion: "2024-01-28",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2024-01-17T09:15:00Z",
  },
  {
    id: 4,
    dateReceived: "2024-01-18",
    dateSent: "2024-01-23",
    productCode: "LUMI-004",
    deviceName: "Lumi Motion Detector",
    distributor: "Nhà phân phối Miền Bắc",
    distributorPhone: "0901234567",
    distributorEmail: "mien-bac@lumi.vn",
    errorDescription:
      "Cảm biến không hoạt động, không phát hiện chuyển động trong phạm vi 5m. Thiết bị không gửi tín hiệu cảnh báo.",
    repairStatus: "completed",
    shippingStatus: "shipped",
    viettelTrackingCode: "VTP240118004",
    estimatedCompletion: "2024-01-23",
    actualCompletion: "2024-01-22",
    repairNotes: "Đã thay thế cảm biến PIR và hiệu chỉnh độ nhạy. Kiểm tra hoạt động bình thường trong phạm vi 8m.",
    repairCost: 120000,
    partsCost: 120000,
    createdAt: "2024-01-18T11:20:00Z",
  },
  {
    id: 5,
    dateReceived: "2024-01-19",
    productCode: "LUMI-005",
    deviceName: "Lumi Smart Switch",
    distributor: "Nhà phân phối Đông Nam Bộ",
    distributorPhone: "0904567890",
    distributorEmail: "dong-nam-bo@lumi.vn",
    errorDescription:
      "Không điều khiển được từ xa qua app mobile. Công tắc hoạt động thủ công nhưng mất kết nối wireless.",
    repairStatus: "in-progress",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP240119005",
    estimatedCompletion: "2024-01-26",
    repairNotes: "Đang cập nhật firmware và kiểm tra kết nối Bluetooth/WiFi",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2024-01-19T16:45:00Z",
  },
  {
    id: 6,
    dateReceived: "2024-01-20",
    productCode: "LUMI-006",
    deviceName: "Lumi Door Sensor",
    distributor: "Nhà phân phối Miền Trung",
    distributorPhone: "0903456789",
    distributorEmail: "mien-trung@lumi.vn",
    errorDescription: "Cảm biến cửa không báo khi mở/đóng. Pin yếu và mất tín hiệu liên tục.",
    repairStatus: "completed",
    shippingStatus: "waiting-shipper",
    viettelTrackingCode: "VTP240120006",
    estimatedCompletion: "2024-01-25",
    actualCompletion: "2024-01-24",
    repairNotes: "Đã thay pin và hiệu chỉnh cảm biến từ. Kiểm tra hoạt động ổn định.",
    repairCost: 80000,
    partsCost: 80000,
    createdAt: "2024-01-20T08:30:00Z",
  },
  {
    id: 7,
    dateReceived: "2024-01-21",
    productCode: "LUMI-007",
    deviceName: "Lumi Smart Plug",
    distributor: "Nhà phân phối Miền Nam",
    distributorPhone: "0902345678",
    distributorEmail: "mien-nam@lumi.vn",
    errorDescription: "Ổ cắm thông minh không điều khiển được qua app. Đèn LED không sáng.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP240121007",
    estimatedCompletion: "2024-01-30",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2024-01-21T13:45:00Z",
  },
  {
    id: 8,
    dateReceived: "2024-01-22",
    productCode: "LUMI-008",
    deviceName: "Lumi Light Dimmer",
    distributor: "Nhà phân phối Đông Nam Bộ",
    distributorPhone: "0904567890",
    distributorEmail: "dong-nam-bo@lumi.vn",
    errorDescription: "Dimmer không điều chỉnh được độ sáng. Đèn chỉ bật/tắt hoàn toàn.",
    repairStatus: "in-progress",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP240122008",
    estimatedCompletion: "2024-01-29",
    repairNotes: "Đang kiểm tra mạch điều khiển PWM",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2024-01-22T11:20:00Z",
  },
  {
    id: 9,
    dateReceived: "2025-06-19",
    productCode: "LUMI-009",
    deviceName: "Driver Đèn",
    distributor: "CTY TNHH CÔNG NGHỆ THÔNG MINH NHÀ AN NHIÊN",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "Driver đèn không hoạt động, không cấp nguồn Mo nguồn cho đèn.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP250619009",
    estimatedCompletion: "2025-06-26",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-19T09:00:00Z",
  },
  {
    id: 10,
    dateReceived: "2025-06-21",
    productCode: "LUMI-010",
    deviceName: "Công tắc",
    distributor: "CTY TNHH NHÀ THÔNG MINH HOMEQ",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "Công tắc không phản hồi khi điều khiển từ xa.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP250621010",
    estimatedCompletion: "2025-06-28",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-21T09:00:00Z",
  },
  {
    id: 11,
    dateReceived: "2025-06-25",
    productCode: "LUMI-011",
    deviceName: "Remote",
    distributor: "CTY TNHH CÔNG NGHỆ 4TU",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "Remote không kết nối với thiết bị, không điều khiển được.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP250625011",
    estimatedCompletion: "2025-07-02",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-25T09:00:00Z",
  },
  {
    id: 12,
    dateReceived: "2025-06-25",
    productCode: "LUMI-012",
    deviceName: "Công tắc",
    distributor: "CTY TNHH DỊCH VỤ THÔNG TIN VÀ GIẢI PHÁP CÔNG NGHỆ TDL",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "Công tắc không hoạt động khi nhấn nút thủ công hoặc qua ứng dụng.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP250625012",
    estimatedCompletion: "2025-07-02",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-25T09:00:00Z",
  },
  {
    id: 13,
    dateReceived: "2025-06-25",
    productCode: "LUMI-013",
    deviceName: "Công tắc",
    distributor: "CTY TNHH CÁP ĐIỆN XANH",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "Công tắc mất kết nối WiFi, không điều khiển từ xa được.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP250625013",
    estimatedCompletion: "2025-07-02",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-25T09:00:00Z",
  },
  {
    id: 14,
    dateReceived: "2025-06-25",
    productCode: "LUMI-014",
    deviceName: "AI Hub",
    distributor: "CTY TNHH CÔNG NGHỆ THÔNG MINH NHÀ AN NHIÊN",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "AI Hub không nhận diện lệnh thoại, kết nối không ổn định.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "VTP250625014",
    estimatedCompletion: "2025-07-02",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-25T09:00:00Z",
  },
  {
    id: 15,
    dateReceived: "2025-06-25",
    productCode: "LUMI-015",
    deviceName: "CB hiện diện, CB hồng ngoại",
    distributor: "Unknown",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "Cảm biến không phát hiện chuyển động hoặc hồng ngoại, hoạt động không ổn định.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "115257558278",
    estimatedCompletion: "2025-07-02",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-25T09:00:00Z",
  },
  {
    id: 16,
    dateReceived: "2025-06-25",
    productCode: "LUMI-016",
    deviceName: "Thiết bị điện",
    distributor: "Unknown",
    distributorPhone: "",
    distributorEmail: "",
    errorDescription: "Thiết bị điện không hoạt động, không cấp nguồn hoặc mất kết nối.",
    repairStatus: "not-started",
    shippingStatus: "not-sent",
    viettelTrackingCode: "115276011128",
    estimatedCompletion: "2025-07-02",
    repairNotes: "",
    repairCost: 0,
    partsCost: 0,
    createdAt: "2025-06-25T09:00:00Z",
  },
]

// Admin credentials
const adminCredentials = {
  email: "admin@lumi.vn",
  password: "admin123",
}

// Distributor list
const distributors = [
  "CTY CỔ PHẦN TẬP ĐOÀN ĐẦU TƯ KOB AN CƯ",
  "CTY CP LUMI MIỀN NAM",
  "CTY CP CÔNG NGHỆ THÔNG MINH THIÊN ÂN",
  "Công ty TNHH Minh Trúc Home",
  "CTY TNHH KIẾN TRÚC XÂY DỰNG PHÁT TRIỂN ĐỊA ỐC HOÀNG GIA",
  "CTY TNHH MỘT THÀNH VIÊN 836",
  "CTY TNHH DV CÔNG NGHỆ MLV SMART",
  "CTY TNHH MỘT THÀNH VIÊN THƯƠNG MẠI XÂY DỰNG TRẦN THÀNH",
  "CTY TNHH CÔNG NGHỆ THÔNG MINH NHÀ AN NHIÊN",
  "CTY TNHH CÔNG NGHỆ ĐIỆN THÔNG MINH HOÀNG PHÁT",
  "CTY TNHH ĐIỆN NƯỚC ĐỒNG PHÁT",
  "Cty TNHH CÔNG NGHỆ MEKOTECH",
  "CTY TNHH DỊCH VỤ THÔNG TIN VÀ GIẢI PHÁP CÔNG NGHỆ TDL",
  "CTY TNHH CÁP ĐIỆN XANH",
  "CTY TNHH CÔNG NGHỆ 4TU",
  "CTY TNHH MỘT THÀNH VIÊN LƯU PHONG",
  "CTY TNHH MỘT THÀNH VIÊN HOÀNG NHẬT VÂN",
  "CTY TNHH THIẾT BỊ CÔNG NGHỆ THIÊN PHÚC QUÝ",
  "CTY TNHH XÂY DỰNG THIẾT KẾ SMARTCITY",
  "CTY TNHH TRUYỀN THÔNG CVT",
  "CTY TNHH GIẢI PHÁP CÔNG NGHỆ THÔNG MINH VIỆT SUN",
  "CÔNG TY TNHH CÔNG NGHỆ PHÚ VINH IOT",
  "CTY TNHH TƯ VẤN THƯƠNG MẠI NHÀ THÔNG MINH",
  "CTY TNHH THÁI THIÊN DI",
  "Công ty TNHH Huy Phát",
  "Công ty TNHH smarthome Minh Phong",
  "CTY TNHH NHÀ THÔNG MINH HOMEQ",
  "CTY TNHH KỸ THUẬT CÔNG NGHỆ MINH ĐẠT",
  "CTY TNHH THIẾT BỊ CÔNG NGHỆ GIA BẢO",
  "CTY TNHH TM DV PHÚ THÁI",
  "CTY TRÁCH NHIỆM HỮU HẠN HOOMI",
  "CTY TNHH HAPPY SMARTHOME",
  "Công Ty TNHH Công Nghệ Phong Nam IOT",
  "CTY CỔ PHẦN ĐẦU TƯ XÂY DỰNG VÀ THIẾT KẾ NHÀ THÔNG MINH GIA ÂN",
  "CTY TNHH ĐỨC HÒA IOT",
  "CTY TNHH CÔNG NGHỆ ASIS",
  "CTY TNHH LUMI SÀI GÒN",
  "CTY TNHH CÔNG NGHỆ THÔNG MINH NGỌC HÂN",
  "Gia Tuấn Technical",
  "CTY TNHH MTV SẢN XUẤT THƯƠNG MẠI DỊCH VỤ TÂM PHÁT",
  "Minh Khang - Intelhouse",
  "CTY TNHH GIẢI PHÁP NHÀ THÔNG MINH CHUYÊN NGHIỆP TOZ",
  "CTY TNHH TM DV GIẢI PHÁP IOT TƯỜNG PHÁT",
  "CTY TNHH 247 ĐỒNG THÁP",
  "Công ty CP công nghệ xây dựng Đà Lạt",
  "Hòa T&S",
  "Công ty TNHH đầu tư xây dựng KING HOUSE",
  "Anh Biên",
  "CT Quang Hòa Bình Phước",
  "LUMI VPMN",
  "Trương Công Tín",
  "CTY TNHH ATECKCO",
  "Hiếu Hạnh",
  "Tin Học Huy Bảo",
  "Lumi Hoàng Anh",
  "Kim Tiến Khang",
  "CTY TNHH TM-DV-TK-XD TRANG THANH",
  "CTY TNHH Gấu Vua",
]

// Export for use in other files
if (typeof module !== "undefined" && module.exports) {
  module.exports = { mockProducts, adminCredentials, distributors }
}